
DECLARE
    V_FIRST_NAME VARCHAR2(50);
    V_LAST_NAME VARCHAR2(50);
    V_EMAIL VARCHAR2(100);
    V_GRADE_LEVEL NUMBER;
    V_GPA NUMBER;
BEGIN
    SCHOOL_SCHEMA.GET_STUDENT_INFO('2001 OR 1=1', V_FIRST_NAME, V_LAST_NAME, V_EMAIL, V_GRADE_LEVEL, V_GPA);
    DBMS_OUTPUT.PUT_LINE('SUCCESS: Injection worked (this is bad)');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('BLOCKED: ' || SQLERRM);
END;
/